- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install package
    ansible.bulitin.package:
      name:"{{item}}"
      state: installed
    loop:
    - nginx
    - postfix
    - mailx