- name: install packages
  hosts: mongodb
  become: yes
  tasks:
  - name: install package
    ansible.builtin.package:
      name: "{{item}}"
      state: installed
      #list of string
    loop:
    - nginx
    - postfix
    - mailx