# playbook is list of plays, always it should with -
- name: ping the node
  hosts: mongodb
# this is list of tasks/modules/collections
  tasks: 
    - name: pinging the node
      ansible.builtin.debug:
        msg: "this is my playbook"
