- name: variables from files
  hosts: localhost #managing the ansible server
  vars_files:
  - variables.yaml
  tasks:
  - name: printing variables
    ansible.builtin.debug:
      msg: "we are learning {{Name}}, duration is: {{duration}}, trainer is: {{trainer}}"
   